# Generated by Django 5.0 on 2024-01-17 11:10

import portfolios.listings.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_auto_20240115_1322"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardetails",
            name="manufacture_date",
        ),
        migrations.AddField(
            model_name="cardetails",
            name="manufacture_year",
            field=models.IntegerField(
                choices=portfolios.listings.models.CarDetails.manufacture_years,
                default=0,
            ),
            preserve_default=False,
        ),
    ]
