# Generated by Django 5.0 on 2024-01-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_remove_cardetails_manufacture_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardetails",
            name="options",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="options", to="listings.caroption"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Inactive"),
                    (1, "Active"),
                    (2, "Draft"),
                    (3, "Reserved"),
                    (4, "Sold"),
                    (5, "Removed"),
                    (6, "Reported"),
                    (7, "under review"),
                ],
                default=2,
            ),
        ),
    ]
