# Generated by Django 5.0 on 2024-01-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0004_alter_cardetails_options_alter_listing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardetails",
            name="color",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="cardetails",
            name="color_interior",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="cardetails",
            name="num_doors",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cardetails",
            name="num_seats",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cardetails",
            name="variant",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
