# Generated by Django 5.0 on 2024-08-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0008_alter_cardetails_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardetails",
            name="body_type",
            field=models.CharField(
                choices=[
                    ("C", "Compact"),
                    ("CO", "Convertible"),
                    ("COU", "Coupe"),
                    ("SUV", "SUV"),
                    ("SW", "Station wagon"),
                    ("S", "Sedan"),
                    ("V", "Van"),
                    ("T", "Transporter"),
                    ("O", "Overig"),
                ],
                default="C",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="cardetails",
            name="condition",
            field=models.CharField(choices=[("N", "New"), ("U", "Used"), ("C", "Classic")], default="U", max_length=1),
        ),
        migrations.AlterField(
            model_name="cardetails",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("B", "Benzine"),
                    ("D", "Diesel"),
                    ("L", "LPG"),
                    ("C", "CNG"),
                    ("2", "Elektro/Benzine"),
                    ("3", "Elektro/Diesel"),
                    ("M", "Ethanol"),
                    ("E", "Elektrisch"),
                    ("H", "Waterstof"),
                    ("O", "Overig"),
                ],
                default="B",
                max_length=1,
            ),
        ),
    ]
