# Generated by Django 5.0 on 2024-01-23 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0005_alter_cardetails_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingmodellease",
            name="annual_kms",
            field=models.IntegerField(
                choices=[
                    (5000, 5000),
                    (7500, 7500),
                    (10000, 10000),
                    (12000, 12000),
                    (15000, 15000),
                    (20000, 20000),
                    (25000, 25000),
                    (30000, 30000),
                    (35000, 35000),
                    (40000, 40000),
                ],
                default=0,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricingmodellease",
            name="lease_company",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricingmodellease",
            name="lease_period",
            field=models.DateField(default=datetime.datetime(2024, 1, 23, 21, 7, 21, 291423)),
            preserve_default=False,
        ),
    ]
