# Generated by Django 5.0 on 2024-01-17 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lease_finder_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserCustomisation",
        ),
    ]
